//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAXI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    [MetadataType(typeof(CustomerDB))]

    public partial class CustomerDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerDB()
        {
            this.information_OrderDB = new HashSet<information_OrderDB>();
        }

        [Remote("IsCusAvailable", "Customers", ErrorMessage = "本學號已被註冊")]
        [Required(ErrorMessage = "必須填入您的學號")]
        [RegularExpression(@"[A]+[A0-9]*$", ErrorMessage = "開頭需為A英文字母")]
        [MinLength(8, ErrorMessage = "需要為8碼"), MaxLength(8, ErrorMessage = "最多為8碼")]
        [Display(Name = "學號")]
        public string Cus_ID { get; set; }
        [Required(ErrorMessage = "必須填入真實姓名")]
        [StringLength(5, ErrorMessage = "最多輸入五個中文字")]
        [Display(Name = "姓名")]
        public string Cus_Name { get; set; }
        [Required(ErrorMessage = "必須輸入電話")]
        [DataType(DataType.PhoneNumber)]
        public string Cus_Phone { get; set; }
        [Required(ErrorMessage = "必須輸入密碼")]
        [Display(Name = "密碼")]
        [DataType(DataType.Password)]
        //[StringLength(30, MinimumLength = 6, ErrorMessage = "會員帳號的長度需再6~30個字元內！")]
        //[RegularExpression(@"[a-zA-Z]+[a-zA-Z0-9]*$", ErrorMessage = "密碼僅能有英文或數字，且開頭需為英文字母！")]
        [MaxLength(20, ErrorMessage = "最多只能設20個字!!!")]
        public string Cus_Password { get; set; }
        public string Cus_Sex { get; set; }
        [DataType(DataType.Upload)]
        public string Cus_Photo { get; set; }
        public string Cus_Email { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<information_OrderDB> information_OrderDB { get; set; }
    }
}
