//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAXI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class DriverDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DriverDB()
        {
            this.information_OrderDB = new HashSet<information_OrderDB>();
        }

        public int Dr_Num { get; set; }
        [Remote("IsCusAvailable", "Drivers", ErrorMessage = "此帳號已被註冊")]
        [Required(ErrorMessage = "必須填入您的帳號")]
        [MinLength(4, ErrorMessage = "最少為4碼英文字母加數字"), MaxLength(16, ErrorMessage = "最多為16碼英文字母加數字")]
        [RegularExpression(@"[a-zA-Z]+[a-zA-Z0-9]*$", ErrorMessage = "僅能有英文或數字，且開頭需為英文字母！")]
        [Display(Name = "帳號")]
        public string Dr_ID { get; set; }
        [Required(ErrorMessage = "必須填入真實姓名")]
        [StringLength(5, ErrorMessage = "最多輸入五個中文字")]
        [Display(Name = "姓名")]
        public string Dr_Name { get; set; }
        [Required(ErrorMessage = "必須輸入電話")]
        [Phone]
        [Display(Name = "電話")]
        public string Dr_Phone { get; set; }
        [Required(ErrorMessage = "必須輸入密碼")]
        [Display(Name = "密碼")]
        [DataType(DataType.Password)]
        //[StringLength(30, MinimumLength = 6, ErrorMessage = "會員帳號的長度需再6~30個字元內！")]
        //[RegularExpression(@"[a-zA-Z]+[a-zA-Z0-9]*$", ErrorMessage = "密碼僅能有英文或數字，且開頭需為英文字母！")]
        [MaxLength(20, ErrorMessage = "最多只能設20個字!!!")]
        public string Dr_Password { get; set; }
        [Required(ErrorMessage = "必須選擇性別")]
        [Display(Name = "性別")]
        public string Dr_Sex { get; set; }
        [Required]
        [Display(Name = "大頭貼")]
        public string Dr_Photo { get; set; }

        [Display(Name = "駕照")]
        public string Dr_License { get; set; }

        [Display(Name = "行照")]
        public string Dr_vehicle_license { get; set; }
        [Display(Name = "良民證")]
        public string Dr_good_citizen { get; set; }
        [Display(Name = "計程車駕照")]
        public string Dr_taxi_driver_license { get; set; }
        public Nullable<int> Order_Num { get; set; }

        public string Dr_Email { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<information_OrderDB> information_OrderDB { get; set; }
    }
}
