//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAXI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationDB
    {
        public int Ev_Num { get; set; }
        public Nullable<int> Order_Num { get; set; }
        public string Ev_Estar { get; set; }
        public string Ev_evaluation { get; set; }
    
        public virtual information_OrderDB information_OrderDB { get; set; }

        public virtual DriverDB DriverDB { get; set; }
    }
}
