//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAXI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using ITAXI.Utilities;


    public partial class information_OrderDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public information_OrderDB()
        {
            this.EvaluationDB = new HashSet<EvaluationDB>();
        }
    
        public int Order_Num { get; set; }
        public string Dr_ID { get; set; }
        public string Cus_ID { get; set; }
        public string Ord_Status { get; set; }
        public string Ord_Type { get; set; }
        public string Ord_date { get; set; }
        public byte Ord_Money { get; set; }
        public System.TimeSpan Boarding_Time { get; set; }
        [NotEqualTo("Drop_off_location", ErrorMessage = "上下車地點不可相同")]
        public string Boarding_Location { get; set; }
        public Nullable<System.TimeSpan> Drop_off_Time { get; set; }
        [NotEqualTo("Boarding_Location", ErrorMessage = "上下車地點不可相同")]
        public string Drop_off_location { get; set; }
        public Nullable<System.TimeSpan> Journey_Time { get; set; }
        public string Ord_Numpeople { get; set; }
        public string Ord_Classification { get; set; }
    
        public virtual CustomerDB CustomerDB { get; set; }
        public virtual DriverDB DriverDB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationDB> EvaluationDB { get; set; }
    }
}
